server:
  port: 8082
  servlet:
    context-path: /springboot
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小 最大连接数  和最小
      initial-size: 10
      max-active: 100
      min-idle: 10
      #连接超时等待时间
      max-wait: 60001
      # 是否开启PSCache
      pool-prepared-statements: false
      #配置间隔多久进行一次检查 检查是否有需要关闭的连接
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      #配置一些扩展插件22
      filters: stat,wall,log4j2
  cache:
    type: REDIS
  redis:
    port: 6379
    host: localhost
    password: dnc.2009
    database: 8
    timeout: 600
    lettuce:
      pool:
        #连接池最大数
        max-active: 50
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  #mapper.xml所在位置
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
    callSettersOnNulls: true
    jdbcTypeForNull: VARCHAR

logging:
  level:
    com:
      neuedu:
        demo:
          user:
            mapper: debug
pagehelper:
  helper-dialect: mysql #数据库方言
  reasonable: true      #分页合理化
  support-methods-arguments: true #是否支持接口参数来传递分页参数，默认false
  page-size-zero: true #当设置为true的时候，如果pagesize设置为0（或RowBounds的limit=0），就不执行分页，返回全部结果




